enabled=true
driverName=VK70xNMC_DAQ2.dll
tcpPort=8234
equipmentNo=M001-1
mci=0
samplingFrequency=5000
acquisitionIntervalMillis=10000
acquisitionDurationMillis=1000
readMode=1
readModeTimeout=100
historySize=30
