enabled=true
adminUrl=jdbc:mysql://127.0.0.1:3306/?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai
url=jdbc:mysql://127.0.0.1:3306/DB_SingalAys?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai
user=root
password=1234
driverClass=com.mysql.cj.jdbc.Driver
databaseName=DB_SingalAys
